# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.Firestore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'


  # Pods for J.Firestore

  target 'J.FirestoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.FirestoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
